<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-20T12:53:14 IST" name="Default suite" finished-at="2023-11-20T12:53:14 IST" duration-ms="155">
    <groups>
    </groups>
    <test started-at="2023-11-20T12:53:14 IST" name="Default test" finished-at="2023-11-20T12:53:14 IST" duration-ms="155">
      <class name="com.app.TDD.demo.EmailValidatorTest">
        <test-method signature="testEmailLengthOutOfRange()[pri:0, instance:com.app.TDD.demo.EmailValidatorTest@16a0ee18]" started-at="2023-11-20T12:53:14 IST" name="testEmailLengthOutOfRange" finished-at="2023-11-20T12:53:14 IST" duration-ms="20" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEmailLengthOutOfRange -->
        <test-method signature="testInvalidEmail()[pri:0, instance:com.app.TDD.demo.EmailValidatorTest@16a0ee18]" started-at="2023-11-20T12:53:14 IST" name="testInvalidEmail" finished-at="2023-11-20T12:53:14 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidEmail -->
        <test-method signature="testValidEmail()[pri:0, instance:com.app.TDD.demo.EmailValidatorTest@16a0ee18]" started-at="2023-11-20T12:53:14 IST" name="testValidEmail" finished-at="2023-11-20T12:53:14 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidEmail -->
        <test-method signature="testValidEmailWithoutDomainValidation()[pri:0, instance:com.app.TDD.demo.EmailValidatorTest@16a0ee18]" started-at="2023-11-20T12:53:14 IST" name="testValidEmailWithoutDomainValidation" finished-at="2023-11-20T12:53:14 IST" duration-ms="30" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Domain is not valid expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Domain is not valid expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at com.app.TDD.demo.EmailValidatorTest.testValidEmailWithoutDomainValidation(EmailValidatorTest.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidEmailWithoutDomainValidation -->
      </class> <!-- com.app.TDD.demo.EmailValidatorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
